name = "M_messages"
version = "0.1.0"
license = "license"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dependencies]

M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
M_anything = { git = "https://github.com/urbanjost/M_anything.git" }

[dev-dependencies]
M_time = { git = "https://github.com/urbanjost/M_time.git" }

#[[executable]]
#name="tat"
#source-dir="app"
#main="tat.f90"
#[executable.dependencies]
#M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }
