name = "M_Compare_Float_Numbers"
version = "0.1.0"
license = "MIT"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2021, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dependencies]
M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
